name: VTS Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.8.4
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        run: earthly --ci --use-inline-cache ./trajectory_native+vts-all-platforms
      - name: Build and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: earthly --ci --use-inline-cache --save-inline-cache --push ./trajectory_native+vts-all-platforms